# -*- coding: utf-8 -*-
CAMEO_CODE = {
        "01":
        {
            "make statement": "010",
            "decline comment": "011",
            "make pessimistic comment": "012",
            "make optimistic comment": "013",
            "consider policy option": "014",
            "acknowledge or claim responsibility": "015",
            "deny responsibility": "016",
            "engage in symbolic act": "017",
            "make empathetic comment": "018",
            "express accord": "019",
            "make public statement": "01"
        },
        "02":
        {
            "appeal": "02",
            "make an appeal or request": "020",
            "appeal for material cooperation": "021",
            "appeal for economic cooperation": "0211",
            "appeal for military cooperation": "0212",
            "appeal for judicial cooperation": "0213",
            "appeal for intelligence": "0214",
            "appeal for diplomatic cooperation": "022",
            "appeal for aid": "023",
            "appeal for economic aid": "0231",
            "appeal for military aid": "0232",
            "appeal for humantitarian aid": "0233",
            "appeal for military protection or peacekeeping": "0234",
            "appeal for political reform": "024",
            "appeal for change in leadership": "0241",
            "appeal for policy change": "0242",
            "appeal for rights": "0243",
            "appeal for change in institutions, regime": "0244",
            "appeal to yield": "025",
            "appeal for easing of administrative sanctions": "0251",
            "appeal for easing of political dissent": "0252",
            "appeal for release of persons or property": "0253",
            "Appeal for easing of economic sanctions, boycott, or embargo": "0254",
            "Appeal for target to allow international involvement": "0255",
            "Appeal for de-escalation of military engagement": "0256",
            "Appeal to others to meet or negotiate": "026",
            "Appeal to others to settle dispute": "027",
            "Appeal to engage in or accept mediation": "028"
        },
        "11": {
                "Find guilty or liable (legally)": "116",
                "Disapprove, not specified below": "110",
            "DISAPPROVE": "11",
            "Criticize or denounce": "111",
            "Accuse of aggression": "1123",
            "Bring lawsuit against": "115",
            "Accuse of crime, corruption": "1121",
            "Complain officially": "114",
            "Rally opposition against": "113",
            "Accuse of espionage, treason": "1125",
            "Accuse, not specified below": "112",
            "Accuse of war crimes": "1124", "Accuse of human rights abuses": "1122"}, "03": {"Express intent to change policy": "0342", "Express intent to allow international involvement (non-mediation)": "0355", "Express intent to change institutions, regime": "0344", "Express intent to de-escalate military engagement": "0356", "Express intent to mediate": "039", "Express intent to ease administrative sanctions": "0351", "Express intent to provide economic aid": "0331", "Express intent to engage in diplomatic cooperation (such as policy support)": "032", "Express intent to cooperate militarily": "0312", "Express intent to settle dispute": "037", "Express intent to institute political reform, not specified below": "034", "Express intent to provide rights": "0343", "Express intent to accept mediation": "038", "Express intent to cooperate on intelligence": "0314", "Express intent to ease popular dissent": "0352", "Express intent to provide humanitarian aid": "0333", "Express intent to cooperate on judicial matters": "0313", "Express intent to cooperate economically": "0311", "Express intent to provide material aid, not specified below": "033", "Express intent to provide military protection or peacekeeping": "0334", "Express intent to release persons or property": "0353", "Express intent to ease economic sanctions, boycott, or embargo": "0354", "Express intent to change leadership": "0341", "Express intent to yield, not specified below": "035", "Express intent to meet or negotiate": "036", "Express intent to provide military aid": "0332", "Express intent to engage in material cooperation, not specified below": "031", "Express intent to cooperate, not specified below": "030"}, "13": {"Threaten to ban political parties or politicians": "1322", "Threaten to halt mediation": "135", "Threaten with military force, not specified below": "138", "Threaten non-force, not specified below": "131", "Threaten occupation": "1382", "Threaten to halt negotiations": "134", "Threaten with restrictions on political freedoms": "1321", "Threaten to impose state of emergency or martial law": "1324", "Threaten with political dissent, protest": "133", "Threaten to impose curfew": "1323", "Threaten with sanctions, boycott, embargo": "1312", "THREATEN": "13", "Threaten with repression": "137", "Threaten with administrative sanctions, not specified below": "132", "Threaten unconventional violence": "1383", "Threaten to halt international involvement (non-mediation)": "136", "Threaten conventional attack": "1384", "Threaten to reduce or break relations": "1313", "Threaten to reduce or stop aid": "1311", "Threaten blockade": "1381", "Threaten attack with WMD": "1385", "Threaten, not specified below": "130", "Give ultimatum": "139"}, "12": {"Reject request for policy change": "1232", "Reject plan, agreement to settle dispute": "127", "Refuse to ease economic sanctions, boycott, or embargo": "1244", "Reject request for humanitarian aid": "1223", "Reject economic cooperation": "1211", "Reject, not specified below": "120", "Refuse to ease popular dissent": "1242", "Reject request for rights": "1233", "Reject request for change in leadership": "1231", "Refuse to de-escalate military engagement": "1246", "Reject request for change in institutions, regime": "1234", "Reject request for military aid": "1222", "Veto": "129", "Defy norms, law": "128", "Reject military cooperation": "1212", "Reject request or demand for material aid, not specified below": "122", "Reject request for military protection or peacekeeping": "1224", "Refuse to allow international involvement (non mediation)": "1245", "Reject request for economic aid": "1221", "Reject proposal to meet, discuss, or negotiate": "125", "Reject material cooperation": "121", "Reject mediation": "126", "Refuse to yield, not specified below": "124", "Refuse to ease administrative sanctions": "1241", "REJECT": "12", "Reject request or demand for political reform, not specified below": "123", "Refuse to release persons or property": "1243"}, "06": {"Engage in judicial cooperation": "063", "Share intelligence or information": "064", "ENGAGE IN MATERIAL COOPERATION": "06", "Cooperate militarily": "062", "Engage in material cooperation, not specified below": "060", "Cooperate economically": "061"}, "07": {"Provide aid, not specified below": "070", "Provide economic aid": "071", "Provide humanitarian aid": "073", "Provide military aid": "072", "Grant asylum": "075", "Provide military protection or peacekeeping": "074", "PROVIDE AID": "07"}, "04": {"Host a visit": "043", "Discuss by telephone": "041", "Make a visit": "042", "CONSULT": "04", "Mediate": "045", "Engage in negotiation": "046", "Consult, not specified below": "040", "Meet at a \u201dthird\u201d location": "044"}, "05": {"Engage in diplomatic cooperation, not specified below": "050", "Grant diplomatic recognition": "054", "Forgive": "056", "Sign formal agreement": "057", "Apologize": "055", "ENGAGE IN DIPLOMATIC COOPERATION": "05", "Praise or endorse": "051", "Rally support on behalf of": "053", "Defend verbally": "052"}, "08": {"Demobilize armed forces": "0873", "Ease political dissent": "082", "Ease restrictions on political freedoms": "0811", "Accede to demands for change in policy": "0832", "Retreat or surrender militarily": "0874", "Ease curfew": "0813", "Return, release, not specified below": "084", "Ease ban on political parties or politicians": "0812", "De-escalate military engagement": "087", "Allow humanitarian access": "0863", "Ease state of emergency or martial law": "0814", "Ease economic sanctions, boycott, embargo": "085", "Ease military blockade": "0872", "Accede to demands for change in leadership": "0831", "Return, release property": "0842", "YIELD": "08", "Allow international involvement, not specified below": "086", "Yield, not specified below": "080", "Accede to demands for change in institutions, regime": "0834", "Declare truce, ceasefire": "0871", "Accede to demands for rights": "0833", "Receive deployment of peacekeepers": "0861", "Accede to requests or demands for political reform, not specified below": "083", "Ease administrative sanctions, not specified below": "081", "Receive inspectors": "0862", "Return, release person(s)": "0841"}, "09": {"Investigate human rights abuses": "092", "Investigate military action": "093", "Investigate war crimes": "094", "Investigate, not specified below": "090", "INVESTIGATE": "09", "Investigate crime, corruption": "091"}, "10": {"Demand mediation": "108", "DEMAND": "10", "Demand material cooperation, not specified below": "101", "Demand policy change": "1042", "Demand economic cooperation": "1011", "Demand easing of economic sanctions, boycott, or embargo": "1054", "Demand humanitarian aid": "1033", "Demand, not specified below": "100", "Demand de-escalation of military engagement": "1056", "Demand economic aid": "1031", "Demand easing of political dissent": "1052", "Demand military protection or peacekeeping": "1034", "Demand meeting, negotiation": "106", "Demand rights": "1043", "Demand release of persons or property": "1053", "Demand that target yields, not specified below": "105", "Demand diplomatic cooperation (such as policy support)": "102", "Demand change in leadership": "1041", "Demand political reform, not specified below": "104", "Demand military aid": "1032", "Demand military cooperation": "1012", "Demand judicial cooperation": "1013", "Demand that target allows international involvement (non-mediation)": "1055", "Demand easing of administrative sanctions": "1051", "Demand settling of dispute": "107", "Demand material aid, not specified below": "103", "Demand intelligence cooperation": "1014", "Demand change in institutions, regime": "1044"},
    "14":
        {
            "engage in political dissent":140,
            "engage in civilian protest":1401,
            "demonstrate or rally":141,
            "present demonstrate or rally":141,
            "demonstrate for leadership change":1411,
            "demonstrate or rally for leadership change":1411,
            "demonstrate for policy change":1412,
            "demonstrate or rally for policy change":1412,
            "demonstrate for rights":1413,
            "demonstrate or rally for rights":1413,
            "demonstrate for change in institutions regime":1414,
            "conduct hunger strike":142,
            "present conduct hunger strike":142,
            "conduct hunger strike for leadership change":1421,
            "conduct hunger strike for policy change":1422,
            "conduct hunger strike for rights":1423,
            "hunger strike change in institutions regime":1424,
            "conduct hunger strike change in institutions regime":1424,
            "conduct hunger strike for change in institutions regime":1424,
            "conduct strike or boycott":143,
            "present conduct strike or boycott":143,
            "conduct strike or boycott for leadership change":1431,
            "strike or boycott for leadership change":1431,
            "conduct strike or boycott for policy change":1432,
            "strike or boycott for policy change":1432,
            "conduct strike or boycott for policy change":1432,
            "strike or boycott for rights":1433,
            "conduct strike or boycott for rights":1433,
            "strike or boycott for change in institutions regime":1434,
            "conduct strike or boycott for change in institutions regime":1434,
            "obstruct passage block":144,
            "obstruct passage or block":144,
            "obstruct passage to demand leadership change":1441,
            "obstruct passage for leadership change":1441,
            "obstruct passage to demand policy change":1442,
            "obstruct passage for policy change":1442,
            "obstruct passage to demand rights":1443,
            "obstruct passage for rights":1443,
            "obstruct passage to demand change in institutions, regime":1444,
            "obstruct passage to demand change in institutions regime" :1444,
            "obstruct passage for change in institutions regime":1444,
            "protest violently riot":145,
            "engage in violent protest riot":145,
            "engage in violent protest for leadership change":1451,
            "violently protest for leadership change":1451,
            "engage in violent protest for policy change":1452,
            "engage in violent protest for rights":1453,
            "violently protest for rights":1453,
            "violently protest for policy change":1452,
            "engage in violent protest for change in institutions regime":1454,
            "violently protest for change in institutions regime":1454
        },
        "15":
        {
            "exhibit force posture": "15",
            "demonstrate military or police power": "150",
            "increase police alert status": "151",
            "increase military alert status": "152",
            "mobilize or increase police power": "153",
            "mobilize or increase armed forces": "154"
        },
        "16":
        {
            "reduce relations": "16",
            "reduce or break diplomatic relations": "161",
            "reduce or stop material aid": "162",
            "reduce or stop economic assistance": "1621",
            "reduce or stop military assistance": "1622",
            "reduce or stop humanitarian assistance": "1623",
            "impose embargo, boycott, or sanctions": "163",
            "halt negotiations": "164",
            "halt mediation": "165",
            "expel or withdraw": "166",
            "expel or withdraw peacekeepers": "1661",
            "expel or withdraw inspectors, observers": "1662",
            "expel or withdraw aid agencies": "1663"
        },
        "17":
        {
            "coerce": "170",
            "seize or damage property": "171",
            "confiscate property": "1711",
            "destroy property": "1712",
            "Impose administrative sanctions": "172",
            "Impose restrictions on political freedoms": "1721",
            "Ban political parties or politicians": "1722",
            "impose curfew": "1723",
            "Impose state of emergency or martial law": "1724",
            "Arrest, detain, or charge with legal action": "173",
            "expel or deport individuals": "174",
            "use tactics of violent repression": "175"
        },
        "18":
        {
            "assault": "18",
            "Use unconventional violence": "180",
            "Abduct, hijack, or take hostage": "181",
            "Physically assault": "182",
            "Sexually assault": "1821",
            "Torture": "1822",
            "Kill by physical assault": "1823",
            "Conduct suicide, car, or other non-military bombing": "183",
            "Carry out suicide bombing": "1831",
            "Carry out car bombing": "1832",
            "Carry out roadside bombing": "1833",
            "Use as human shield": "184",
            "Attempt to assassinate": "185",
            "Assassinate": "186"
        },
        "19":
        {
            "fight": "19",
            "Use conventional military force, not specified below": "190",
            "Impose blockade, restrict movement": "191",
            "Occupy territory": "192",
            "Fight with small arms and light weapons": "193",
            "Fight with artillery and tanks": "194",
            "Employ aerial weapons": "195",
            "Violate ceasefire": "196"
        },
        "20":
        {
            "use unconventional mass violence": "20",
            "engage in mass expulsion": "201",
            "engage in mass kills": "202",
            "engage in ethnic cleansing": "203",
            "use weapons of mass destruction": "204",
            "use chemical, biological, or radiological weapons": "2041",
            "detonate nuclear weapons": "2042"
        }
    }
