CAMEO_CODE = {
        "14":
        {
            "engage in political dissent":140, 
            "engage in civilian protest":1401,
            "demonstrate or rally":141,
            "present demonstrate or rally":141,
            "demonstrate for leadership change":1411,
            "demonstrate or rally for leadership change":1411,
            "demonstrate for policy change":1412,
            "demonstrate or rally for policy change":1412,
            "demonstrate for rights":1413,
            "demonstrate or rally for rights":1413,
            "demonstrate for change in institutions regime":1414,
            "conduct hunger strike":142,
            "present conduct hunger strike":142,
            "conduct hunger strike for leadership change":1421,
            "conduct hunger strike for policy change":1422,
            "conduct hunger strike for rights":1423,
            "hunger strike change in institutions regime":1424,
            "conduct hunger strike change in institutions regime":1424,
            "conduct hunger strike for change in institutions regime":1424,
            "conduct strike or boycott":143,
            "present conduct strike or boycott":143,
            "conduct strike or boycott for leadership change":1431, 
            "strike or boycott for leadership change":1431,
            "conduct strike or boycott for policy change":1432,
            "strike or boycott for policy change":1432,
            "conduct strike or boycott for policy change":1432,
            "strike or boycott for rights":1433,
            "conduct strike or boycott for rights":1433,
            "strike or boycott for change in institutions regime":1434,
            "conduct strike or boycott for change in institutions regime":1434,
            "obstruct passage block":144,
            "obstruct passage or block":144,
            "obstruct passage to demand leadership change":1441,
            "obstruct passage for leadership change":1441,
            "obstruct passage to demand policy change":1442,
            "obstruct passage for policy change":1442,
            "obstruct passage to demand rights":1443,
            "obstruct passage for rights":1443,
            "obstruct passage to demand change in institutions, regime":1444,
            "obstruct passage to demand change in institutions regime" :1444,
            "obstruct passage for change in institutions regime":1444,
            "protest violently riot":145,
            "engage in violent protest riot":145,
            "engage in violent protest for leadership change":1451,
            "violently protest for leadership change":1451,
            "engage in violent protest for policy change":1452,
            "engage in violent protest for rights":1453,
            "violently protest for rights":1453,
            "violently protest for policy change":1452,
            "engage in violent protest for change in institutions regime":1454,
            "violently protest for change in institutions regime":1454
        },
        "17":
        {
            "coerce": "170",
            "seize or damage property": "171",
            "confiscate property": "1711",
            "destroy property": "1712",
            "Impose administrative sanctions": "172",
            "Impose restrictions on political freedoms": "1721",
            "Ban political parties or politicians": "1722",
            "impose curfew": "1723",
            "Impose state of emergency or martial law": "1724",
            "Arrest, detain, or charge with legal action": "173",
            "expel or deport individuals": "174",
            "use tactics of violent repression": "175"
        },
        "18":
        {
            "assault": "18",
            "Use unconventional violence": "180",
            "Abduct, hijack, or take hostage": "181",
            "Physically assault": "182",
            "Sexually assault": "1821",
            "Torture": "1822",
            "Kill by physical assault": "1823",
            "Conduct suicide, car, or other non-military bombing": "183",
            "Carry out suicide bombing": "1831",
            "Carry out car bombing": "1832",
            "Carry out roadside bombing": "1833",
            "Use as human shield": "184",
            "Attempt to assassinate": "185",
            "Assassinate": "186"
        }
    }
